#!/usr/bin/python3
import sys
import os
import yaml
from glob import glob
import subprocess
import psutil
from  ipcqueue import posixmq

_REPO_ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_REPO_ROOT, "common"))

args = sys.argv
if 'python' in args[0]:
    args = args[1:]

acqDir = '/home/vandaq/vandaq/acquirer/'
acqLogDir = acqDir+'log/'
collDir = '/home/vandaq/vandaq/collector/' 
collLogDir = collDir+'log/'
submDir =  '/home/vandaq/vandaq/submitter/'
submLogDir = submDir+'log/'
repoDir = '/home/vandaq/vandaq/'
spiderPsdLogDir = repoDir + 'data/spider_psd/log/'
processes = []

config_file_name = '/home/vandaq/vandaq/vandaq_admin.yaml' 
config = None 

try:
    from config_loader import load_yaml_config
    config = load_yaml_config(config_file_name, Loader=yaml.FullLoader)
except Exception:
    print("Cannot load config file " + config_file_name)
    exit()
    
if config:
    acqDir = config['directories']['acquirer_directory']
    acqLogDir = config['directories']['acquirer_log_directory']
    collDir = config['directories']['collector_directory']
    collLogDir = config['directories']['collector_log_directory']
    repoDir = acqDir.rsplit('acquirer', 1)[0] if 'acquirer' in acqDir else repoDir
    spiderPsdLogDir = config['directories'].get(
        'spider_psd_log_directory', repoDir + 'data/spider_psd/log/',
    )


def getAcquirerProcesses():
    ps = []
    for p in psutil.process_iter():
        try:
            status = p.status()
        except Exception as e:
            i=1
        else: 
            if p.status() != 'zombie':
                cmdln = ' '.join(p.cmdline())
                if 'vandaq_acquirer.py' in cmdln:
                    ps.append(p)
    return ps


def getCollectorProcesses():
    ps = []
    for p in psutil.process_iter():
        try:
              status = p.status()
        except Exception as e:
            i=1
        else: 
            if p.status() != 'zombie':
                cmdln = ' '.join(p.cmdline())
                if 'vandaq_collector.py' in cmdln:
                    ps.append(p)
    return ps

def getSpiderPsdIngestProcesses():
    ps = []
    for p in psutil.process_iter():
        try:
            status = p.status()
        except Exception:
            continue
        if p.status() != 'zombie':
            cmdln = ' '.join(p.cmdline())
            if 'spider_psd_ingest.py' in cmdln:
                ps.append(p)
    return ps


def getSubmitterProcesses():
    ps = []
    for p in psutil.process_iter():
        try:
              status = p.status()
        except Exception as e:
            i=1
        else: 
            if p.status() != 'zombie':
                cmdln = ' '.join(p.cmdline())
                if 'vandaq_submitter.py' in cmdln:
                    ps.append(p)
    return ps


def startup(arg=None):
    print('starting VanDAQ processes')
    basedir = acqDir+'config/'
    
    if basedir[-1] != '/':
        basedir += '/'

    this_env = os.environ.copy()
    if config and config['components'] and config['components']['launch_collector']: 
        if arg == None or arg == 'collector':
            collector_config = collDir+'vandaq_collector.yaml'
            if config and ('components' in config) and ('collector_config_file' in config['components']):
                collector_config = collDir+config['components']['collector_config_file']
            cmd = ['python3',collDir+'vandaq_collector.py', collector_config]
            logFileName = collLogDir + 'collector.log'
            logFile = open(logFileName,'a')
            proc = subprocess.Popen(cmd, env=this_env, stdout=logFile, stderr=logFile)
            #proc.wait()
            print('Started collector '+str(cmd)+'   pid='+str(proc.pid))
            processes.append({'cmd':cmd, 'pid':proc.pid})
            if arg == 'collector':
                return

    if config and config['components'] and config['components']['launch_acquirers']:
        acq_configs = [
            p for p in glob(basedir + '*.yaml')
            if '.local.' not in os.path.basename(p)
        ]

        if len(acq_configs) > 0:
            for acq_config in acq_configs:
                if arg != None:
                    if not arg in acq_config.lower():
                        continue
                logFileName = acqLogDir + os.path.basename(acq_config.replace('.yaml',''))
                logFile = open(logFileName,'a')
                cmd = ['python3',acqDir+'vandaq_acquirer.py',acq_config]
                proc = subprocess.Popen(cmd, env=this_env, stdout=logFile, stderr=logFile)
                #proc.wait()
                pid = proc.pid
                print('Started acquirer '+str(cmd)+'   pid='+str(pid))
                processes.append({'cmd':cmd, 'pid':proc.pid})

    if config and config['components'] and config['components']['launch_submitter']: 
        if arg == None or arg == 'submitter':
            submitter_config = submDir+'vandaq_submitter.yaml'
            if config and ('components' in config) and ('submitter_config_file' in config['components']):
                submitter_config = submDir+config['components']['submitter_config_file']
            cmd = ['python3',submDir+'vandaq_submitter.py', submitter_config]
            logFileName = submLogDir + 'submitter.log'
            logFile = open(logFileName,'a')
            proc = subprocess.Popen(cmd, env=this_env, stdout=logFile, stderr=logFile)
            #proc.wait()
            print('Started submitter '+str(cmd)+'   pid='+str(proc.pid))
            processes.append({'cmd':cmd, 'pid':proc.pid})

    if config and config['components'] and config['components'].get('launch_spider_psd_ingest'):
        if arg is None or 'spider' in arg or 'psd' in arg:
            ingest_script = repoDir + 'utils/spider_psd_ingest.py'
            cmd = [
                'python3', ingest_script,
                '--no-move',
                '--log-file', spiderPsdLogDir + 'spider_psd_ingest.log',
            ]
            os.makedirs(spiderPsdLogDir, exist_ok=True)
            logFileName = spiderPsdLogDir + 'spider_psd_ingest.log'
            logFile = open(logFileName, 'a')
            proc = subprocess.Popen(cmd, env=this_env, stdout=logFile, stderr=logFile)
            print('Started spider PSD ingest ' + str(cmd) + '   pid=' + str(proc.pid))
            processes.append({'cmd': cmd, 'pid': proc.pid})
            if arg is not None and ('spider' in arg or 'psd' in arg):
                return


def stop(arg=None):
    print('Stopping VanDAQ processes')
    ps = getCollectorProcesses()
    for p in ps:
        if arg == None or arg == 'collector':
            print('stopping '+' '.join(p.cmdline())+' pid '+str(p.pid)) 
            p.kill()
            p.wait()
    ps = getAcquirerProcesses()
    for p in ps:
        if arg == None or arg in ' '.join(p.cmdline()).lower():
            print('stopping '+' '.join(p.cmdline())+' pid '+str(p.pid)) 
            p.kill()
            p.wait()
    ps = getSubmitterProcesses()
    for p in ps:
        if arg == None or arg == 'submitter':
            print('stopping '+' '.join(p.cmdline())+' pid '+str(p.pid)) 
            p.kill()
            p.wait()
    ps = getSpiderPsdIngestProcesses()
    for p in ps:
        if arg is None or 'spider' in arg or 'psd' in arg:
            print('stopping '+' '.join(p.cmdline())+' pid '+str(p.pid))
            p.kill()
            p.wait()

def status(arg=None):
    print('Looking for VanDAQ processes')
    ps = (
        getCollectorProcesses()
        + getAcquirerProcesses()
        + getSubmitterProcesses()
        + getSpiderPsdIngestProcesses()
    )
    if not ps:
        print('No VanDAQ process running')
    else:
        print('command \t pid \t status')
        for p in ps:
            if arg == None or arg in ' '.join(p.cmdline()).lower():
                line = ' '.join(p.cmdline())+'\t'
                line += str(p.pid)+'\t'
                line += p.status()
                print(line)

queue_name = '/dev-measurements'    

def clear_queue(arg=None):
    try:
        queue = posixmq.Queue(queue_name,  maxsize=50, maxmsgsize=8000)
        num = queue.qsize()
        for i in range(0,num):
            print('.')
            message = queue.get()
        queue.close()
    except Exception as e:
        print('error clearing queue: {}'.format(str(e)))
    else:
        print(f'queue cleared of {num} messages.')
        
    
        
    
commands = {'startup':startup, 'start':startup, 'stop':stop, 'status':status, 'clearqueue': clear_queue}

if len(args) >= 2 and args[1] in commands.keys():
    command = commands[args[1]]
    arg = None
    if len(args) > 2:
        arg = args[2].lower()
    command(arg)
else:
    print('vandaq_admin: no command "' + ' '.join(args[1:]) + '" found')

